### ISSUE TITLE
virtual machine configuration for running the extraction tool 

### ISSUE THREAD

**Issue by S6savahd** [ceurws/lod#11]
process-new-volume can easily be executed from this vm #10 
please specify the configuration using vagrant 

see: https://www.vagrantup.com/docs/provisioning/shell.html

**Comment by liyakun** [comment]
A configuration file for vagrant is created in 'https://github.com/ceurws/ToolsEswc/tree/master/environment', with corresponding shell script.

**Comment by S6savahd** [comment]
thanks Yakun

@s6savahd: check this and make sure all works
