### ISSUE TITLE
Align vocabulary of extracted RDF with vocabulary of latest RDFa

### ISSUE THREAD

**Issue by clange** [ceurws/lod#12]
One thing I forgot to mention in our most recent meeting:

The vocabulary used in the RDF that https://github.com/ceurws/ToolsEswc extracts from the workshop proceedings volumes tables of content should be overlap as much as possible with the vocabulary that the RDFa annotations in workshop proceedings volumes generated with https://github.com/ceurws/ceur-make use.

@S6savahd could you please discuss this with @liyakun?

The latest version of this vocabulary, which will go into production soon, can be seen in http://ceur-ws.org/Vol-1551/. This is the latest version of ceur-make with contributions from @csarven.

**Comment by S6savahd** [comment]
sure.

@liyakun: please have a look, that is easy to understand by doing comparisons between the (re)-used vocabularies of the two outputs. we have done this before for other datasets and results. since I m not available this week, we can schedule a Skype call to discuss this on Monday, suits you?

**Comment by csarven** [comment]
I suggest using http://ceur-ws.org/Vol-1549/ as an example until otherwise noted :)

**Comment by WolfgangFahl** [comment]
obsolete with new parser approach
