### ISSUE TITLE
RDF extraction from legacy proceeding should conform to schema of CEUR-Make

### ISSUE THREAD

**Issue by WolfgangFahl** [ceurws/lod#13]
Goal: RDF Information extraction

Tool-Options:

- Tools of semantic publishing challenge
- http://librdf.org/raptor/rapper.html see Example in clange comment below
- Python Library: https://www.w3.org/2012/pyRdfa/Overview.html

See also #12 (duplicate)

**Comment by clange** [comment]
Here you can see the desired schema, i.e., the schema used by proceedings volumes created with ceur-make: `rapper -i rdfa http://ceur-ws.org/Vol-2549/ -o ntriples` (using http://librdf.org/raptor/rapper.html)

**Comment by WolfgangFahl** [comment]
obsolete with #25
