### ISSUE TITLE
Version handling

### ISSUE THREAD

**Issue by WolfgangFahl** [ceurws/lod#18]
The following script checks which different CEURVERSION tags have been assigned in the past:
```
#
# get all volume directories
#
volumes() {
  for v in $(find . -name "Vol-*" -type d)
  do
    echo "$v"
  done
}


for v in $(volumes)
do
  head -5 $v/index.html  | grep CEURVERSION | cut -f2 -d'=' | cut -f1 -d" "
done

```

The result is:

```
2013-10-11
2013-11-14
2013-12-02
2013-12-11
2014-09-15
2014-09-16
2014-09-17
2014-09-18
2014-10-06
2014-10-12
2015-03-30
2015-04-21
2015-06-14
2015-06-15
2015-06-27	
2015-07-18
2015-09-30
2015-12-02
2016-08-01
2016-11-12
2017-04-04
2018-06-30
2018-08-31
2019-08-01
2020-04-03
```
as of 2020-06-06 of the 2620 Volumes some 1500 have a CEURVERSION indication

**Comment by miselico** [comment]
One aspect to keep in mind is that most pages have gotten som manual modifications. Hence, it is good to also include a small sanity check like a regex before trusting the output.
