### ISSUE TITLE
Extract LOD from all proceedings volumes

### ISSUE THREAD

**Issue by clange** [ceurws/lod#2]
… using https://github.com/ailabitmo/sempubchallenge2014-task1.

Expected output: one large `rdfdb.ttl` file, which will require further processing.

**Comment by S6savahd** [comment]
the error was not important, just one of the links had strange characters, I removed it.

**Comment by S6savahd** [comment]
All data is extracted from all URLs except the removed one! The only thing is that, the data should be extracted once more with new DBpedia dumps but we can use the current extracted data!
