### ISSUE TITLE
update CEUR-WS-LOD data

### ISSUE THREAD

**Issue by VladimirAlexiev** [ceurws/lod#24]
@WolfgangFahl @clange @S6savahd @maxkolchin
Hi! I read https://www.researchgate.net/publication/306231689_CEUR-WS-LOD_Conversion_of_CEUR-WS_Workshops_to_Linked_Data hoping it can help with https://github.com/zotero/translators/issues/2015 (Zotero doesn't have a CEUR extractor).

Unfortunately the data here is last updated 2015/2016, and I don't see the extraction tools.
Could someone please put up the tools, and I'll undertake to process all CEUR in the last 5 years?

(BTW, is this published somewhere as LOD?)

**Comment by WolfgangFahl** [comment]
@VladimirAlexiev  just wrote a personal e-mail to you for clarification.

**Comment by WolfgangFahl** [comment]
@VladimirAlexiev we are directly targeting Wikidata these days see #25
