### ISSUE TITLE
Publish RDF/XML and HTML in LOD style

### ISSUE THREAD

**Issue by clange** [ceurws/lod#5]
Taking the output of #4 publish it from the CEUR-WS.org workshop URLs in the same way as so far done manually for http://ceur-ws.org/Vol-1191/.
1. copy all files to the server (in a reproducable way, i.e. with a Makefile rule)
2. generate appropriate `.htaccess` files.

**Comment by WolfgangFahl** [comment]
Instead of local storage we'll use wikidata see
[Vol-1191 example SMILE 2013](https://www.wikidata.org/wiki/Q113504794)
