### ISSUE TITLE
Missing paper in SemPub16_Task2 Training Dataset TD2

### ISSUE THREAD

**Issue by SreeHarshaRamesh** [ceurws/lod#7]
http://ceur-ws.org/Vol-1405/paper06.pdf is not found on the server. 

Can you please check?

**Comment by angelobo** [comment]
Dear Sree Harsha,
thank you for spotting this. There was a mistake in the URL transcription.

The correct one is: http://ceur-ws.org/Vol-1405/paper-06.pdf   (the web page is now updated).

Thanks again,
Angelo


----------------------------------------------------------------
Angelo Di Iorio, PhD
Department of Computer Science and Engineering
University of Bologna, Bologna (Italy)

WWW: http://www.cs.unibo.it/~diiorio/
Phone: +39 051 2094898
----------------------------------------------------------------

**Comment by SreeHarshaRamesh** [comment]
@angelobo Thanks for the quick fix.
