### ISSUE TITLE
global resources for persons and SAME AS links 

### ISSUE THREAD

**Issue by S6savahd** [ceurws/lod#8]
The aim is for each person, we have a RDF resource that has a URI like http://ceur-ws.org/Vol-1/#Alise owl:sameAs http://ceur-ws.org/persons/Alise .

**Comment by liyakun** [comment]
@S6savahd @clange , I added this RDF resource, like 
```Turtle
<http://ceur-ws.org/Vol-1200/#GiuseppeiDiiFabbrizio> a foaf:Person ;
    = <http://ceur-ws.org/persons/GiuseppeiDiiFabbrizio> ;
    foaf:name "Giuseppe Di Fabbrizio" .
```

**Comment by S6savahd** [comment]
looks good.
