### ISSUE TITLE
global resources for event series

### ISSUE THREAD

**Issue by S6savahd** [ceurws/lod#9]
the URI should be http://ceur-ws.org/series/SePublica 
 and this resource should have pointers to the individual events 
e.g., http://ceur-ws.org/Vol-1155/#part-SePublica

**Comment by liyakun** [comment]
@S6savahd @clange , the series resource is added, and one example is:
```Turtle
<http://ceur-ws.org/Vol-987/#part-IWSECO> a ns3:Workshop ;
    ns1:partOf <http://ceur-ws.org/series/IWSECO> ;
    ns6:title "International Workshop on Software Ecosystems 2013" ;
    ns3:shortTitle "IWSECO" ;
    ns5:edition 5 .

<http://ceur-ws.org/series/IWSECO> ns1:hasPart <http://ceur-ws.org/Vol-505/#part-IWSECO>,
        <http://ceur-ws.org/Vol-746/#part-IWSECO>,
        <http://ceur-ws.org/Vol-879/#part-IWSECO>,
        <http://ceur-ws.org/Vol-987/#part-IWSECO> .
```
Do you think the vocabulary "partOf" and "hasPart" is appropriate?

**Comment by S6savahd** [comment]
the triples look fine, for the vocabularies, I would explore more to find meaningful ones (if any)
with a quick search, I found this: http://vivoweb.org/ontology/core#EventSeries

 ScholarlyData also do not have event series: http://www.essepuntato.it/lode/http://www.scholarlydata.org/ontology/conference-ontology.owl

maybe we can define our own, e.g., :partOfSeries     :isSeries

**Comment by liyakun** [comment]
@S6savahd , as we decide to keep current vocabularies for event series until we find better vocabularies, I changed the label of this issue as enhancement.

**Comment by WolfgangFahl** [comment]
see Series in Wikidata:
#27 [International Workshop on Software Ecosystems ](https://www.wikidata.org/wiki/Q105700301)
#29 [SePublica](https://www.wikidata.org/wiki/Q113505627)
